name: Sync with personal repo

on:
  push:
    branches: ["main"]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_REPO_TOKEN }}
          fetch-depth: 0 # 모든 브랜치와 태그 가져오기
          ref: main

      - name: Add remote URL of personal repo
        run: |
          git remote add personal-repo https://TProgramer:${{ secrets.PERSONAL_REPO_TOKEN }}@github.com/TProgramer/WordSketch-FE
          git config user.name TProgramer
          git config user.email tposter@naver.com

      - name: Push changes to personal repo
        run: |
          git push -f personal-repo main

      - name: Tear down
        run: git remote remove personal-repo
